sb_goals/blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'

urlpatterns = [
    url(r'^tag/(?P<tag>[-\w]+)/', views.tag_view, name="tag"),
    url(r'^category/(?P<category>[-\w]+)/feed/$', views.LatestCategoryFeed(), name="category_feed"),
    url(r'^category/(?P<category>[-\w]+)/', views.category_view, name="category"),
    url(r'^author/(?P<author>[-\w]+)/', views.author_view, name="author"),
    url(r'(?P<blog_slug>[\w-]+)/rss.*/',
        views.LatestEntriesFeed(),
        name="latest_entries_feed"),
    url(r'(?P<blog_slug>[\w-]+)/atom.*/',
        views.LatestEntriesFeedAtom(),
        name="latest_entries_feed_atom"),
]

sb_goals/sb_goals/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path, include
from django.conf.urls import include, url
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls


urlpatterns = [
#     path('', include('homepage.urls')),  # removed old homepage made in Django
    path('dv/', include('data_visualisations.urls')),
    path('tasks/', include('tasks.urls')),
    path('sb_quiver/', include('sb_quiver.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login' ),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout' ),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('sb_quiver/', include('sb_quiver.urls')),
#     path('admin/', admin.site.urls),
    url(r'^django-admin/', admin.site.urls),
    url(r'^admin/', include(wagtailadmin_urls)),
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^', include(wagtail_urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sb_goals/sb_quiver/urls.py
from django.urls import path
from django.urls import path, re_path, include

from .views import (
    BoardListView,
    BoardDetailView,
    BoardCreateView,
    BoardUpdateView,
    BoardDeleteView,
    UserBoardListView
)
from . import views

app_name = 'sb_quiver'

urlpatterns = [
    path('', BoardListView.as_view(), name='sb_quiver-home'),
    path('user/<str:username>/', UserBoardListView.as_view(), name='user-boards'),
    path('board/<int:pk>/', BoardDetailView.as_view(), name='board-detail'),
    path('board/new/', BoardCreateView.as_view(), name='board-create'),
    path('board/<int:pk>/update/', BoardUpdateView.as_view(), name='board-update'),
    path('board/<int:pk>/delete/', BoardDeleteView.as_view(), name='board-delete'),
    path('about/', views.about, name='sb_quiver-about'),
]

sb_goals/tasks/urls.py
from django.urls import path
from django.conf.urls import url

from .views import TaskBarChartData, index, detail, done


app_name = 'tasks'

urlpatterns = [
    path('', index, name='index'),
    path('<int:task_id>/', detail, name='detail'),
    path('<int:task_id>/done/', done, name='done'),
    url(r'^api/taskbarchart/data/$', TaskBarChartData.as_view()),
]

sb_goals/home/models.py
import datetime

from django.db import models
from django.utils import timezone
from tasks.models import Task, TaskAction
from blog.models import BlogPage

from users.models import Profile
from wagtail.contrib.modeladmin.options import ModelAdmin
from wagtail.core.models import Page
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel


class HomePage(Page):
    body = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('body', classname="full"),
    ]

    def get_context(self, request):
        """Update context - includes passing messages/alerts to our homepage
        TODO do we have a user logged in - Only get results if we have. """
        context = super().get_context(request)
        context['welcome_msg'] = ''

        current_month = int( timezone.now().strftime('%-m') )
        current_year = int( timezone.now().strftime('%Y') )
        current_day = int( timezone.now().strftime('%-d') )

        ta_obj = TaskAction()
        has_ta_been_done_today = ta_obj.have_any_tasks_been_done_on_this_day(current_day, current_month, current_year)
        if not has_ta_been_done_today:
            """ Output a message that no tasks have been done yet today """
            context['welcome_msg'] += "You haven't completed any tasks yet today ! <br><br>"

        blogs = BlogPage.objects.live().order_by('first_published_at')
        blogs_current_user = []
        user_id = request.user.id
        for blogpage in blogs:
            if blogpage.owner.id == user_id:
                blogs_current_user.append(blogpage)

        context['username'] = request.user.username

        today = datetime.datetime.today()
        if len(blogs_current_user) is not 0:
            last_blog_index = len(blogs_current_user)-1
            last_blog = blogs_current_user[last_blog_index].first_published_at.replace(tzinfo=None) # removed info to make both dates Naive
            delta = today - last_blog

        if len(blogs_current_user) == 0:
            context['welcome_msg'] += 'Time to go surfing and registering it !<br><br>'
        elif delta.days > 5:
            context['welcome_msg'] += 'You haven\'t been surfing for ' + str(delta.days) + ' days.  SORT IT OUT !!! <br><br>'
        elif not delta.days == 0:
            context['welcome_msg'] += 'It has been ' + str(delta.days) + ' days since your last surf <br><br>'
        else:
            context['welcome_msg'] += 'Yewwwww! Hope you  enjoyed your surf :) <br><br>'

        t = Task()
        worst_performer = t.whats_your_worst_performer_in_timespan(request, 'month')

        context['welcome_msg'] += worst_performer

        return context

class CustomMenu(ModelAdmin):

    def get_list_display(self, request):
        """
        Return a sequence containing the fields/method output to be displayed
        in the list view.
        """
        return self.list_display

    list_display = []

sb_goals/sb_quiver/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image



class Board(models.Model):
    """Let's store our measurements in cm's for now.  """
    title = models.CharField(max_length=100)
    image = models.ImageField(default='default-sb.jpg', upload_to='surfboard_pics')
    notes = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    length = models.FloatField(max_length=5, help_text="Enter in 'cm's")
    width = models.FloatField(max_length=5, help_text="Enter in 'cm's")
    thickness = models.FloatField(max_length=5, default=5, help_text="Enter in 'cm's")
    volume = models.FloatField(max_length=5, null=True, blank=True, help_text="Enter in 'millilitres's.  A calculation will be made for you if you fill in L x W x T" )
    wave_range_start = models.FloatField(max_length=5, null=True, blank=True, help_text="Enter in 'cm's")
    wave_range_end = models.FloatField(max_length=5, null=True, blank=True, help_text="Enter in 'cm's")
    make = models.CharField(max_length=100)
    shaper = models.CharField(max_length=100, null=True, blank=True)
    year = models.CharField(max_length=4, blank=True)

    def __str__(self):
        return f'{self.title} Board'

    def get_absolute_url(self):
        return reverse('sb_quiver:board-detail', kwargs={'pk': self.pk})

#     def save(self, *args, **kwargs):
#         """As we save our Profile we'll check that we're not saving a file that's too large"""
#         super().save(*args, **kwargs)
#
#         if img.height > 800:
#             output_size = (_, 800)
#             img.thumbnail(output_size)
#             img.save(self.image.path)

sb_goals/sb_quiver/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Board


def home(request):

    context = {
        'boards': Board.objects.all()
    }
    return render(request, 'sb_quiver/home.html', context)

class BoardListView(ListView):
    model = Board
    template_name = 'sb_quiver/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'boards'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_queryset(self, *args, **kwargs):
        user = kwargs.pop('user', self.request.user)
        return Board.objects.filter(author=user).order_by('-date_posted')


class UserBoardListView(ListView):
    model = Board
    template_name = 'sb_quiver/user_boards.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'boards'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Board.objects.filter(author=user).order_by('-date_posted')


class BoardDetailView(DetailView):
    model = Board

class BoardCreateView(LoginRequiredMixin, CreateView):
    model = Board
    fields = ['title', 'image', 'length', 'width', 'thickness', 'volume', 'wave_range_start',
            'wave_range_start', 'wave_range_end', 'shaper', 'year', 'make', 'notes']

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.volume = form.instance.width * form.instance.length * 2.5 # we need to put a calculation here
        return super().form_valid(form)

class BoardUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Board
    fields = ['title', 'image', 'length', 'width', 'thickness', 'volume', 'wave_range_start',
                'wave_range_start', 'wave_range_end', 'shaper', 'year', 'make', 'notes']

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.volume = form.instance.width * form.instance.length * 2.5 # we need to put a calculation here
        return super().form_valid(form)

    def test_func(self):
        board = self.get_object()
        if self.request.user == board.author:
            return True
        return False

class BoardDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Board
    success_url = '/'

    def test_func(self):
        board = self.get_object()
        if self.request.user == board.author:
            return True
        return False


def about(request):
    return render(request, 'sb_quiver/about.html', {'title': 'About'})

sb_goals/sb_quiver/templates/sb_quiver/about.html
{% extends "home/base.html" %}
{% load sb_quiver_extras %}
{% block content %}
{% include "sb_quiver/quiver_header.html" %}
<h1>About page</h1>
{% endblock content %}}
<h1>About page</h1>
</body>

sb_goals/sb_quiver/templates/sb_quiver/base.html
{% load static %}
{% load wagtailcore_tags %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'sb_quiver/main.css' %}">

    {% if title %}
    <title>Surfboard Quiver - {{ title }}</title>
    {% else %}
    <title>Surfboard Quiver</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">SB Goals</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="/">Home</a>
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'tasks:index' %}" >Tasks</a>
                    <a class="nav-item nav-link" href="{% url 'sb_quiver:sb_quiver-home' %}">Quiver</a>
                    <a class="nav-item nav-link" href="{% slugurl 'sports-diary' %}">Diary</a>
                    {% endif %}
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <ul class="list-group">
                    {% if user.is_authenticated %}
                    <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{% url 'sb_quiver:board-create' %}">Add to Quiver</a></li>
                    <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{% slugurl 'month' %}">Month view</a></li>
                    <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{% slugurl 'sports-diary' %}">Diary</a></li>
                    <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="admin/pages/add/blog/blogpage/4/">Add a Surf</a></li>
                    {% endif %}
                </ul>
                </p>
            </div>
        </div>
    </div>
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

sb_goals/sb_quiver/templates/sb_quiver/board_confirm_delete.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% include "sb_quiver/quiver_header.html" %}
<div class="content-section nice-padding">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Surfboard</legend>
            <h2>Are you sure you want to delete this entry ?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-danger" href="{% url 'sb_quiver:board-detail' object.id %}" >Cancel</a>
        </div>
    </form>

</div>
{% endblock content %}

sb_goals/sb_quiver/templates/sb_quiver/board_detail.html
{% extends "home/base.html" %}
{% load sb_quiver_extras %}
{% block content %}
{% include "sb_quiver/quiver_header.html" %}
<article class="media content-section nice-padding">
    <div class="media-body">
        <div class="article-metadata">
            <div class="row">
                <div class="col-span-12"><h2 class="article-title">{{ object.title }} - {{ object.make }}</h2></div>
            </div>
            <div class="row">
                <div class="col-span-4">
                    <img class="img-rounded" width="350px" src="{{ board.image.url }}" alt="{{ board.name }}">
                </div>
                <div class="col-span-8">
                    <p class="article-content">{{ object.content }}</p>
                    <ul class="list-group">
                        <li class="list-group-item">Size: {{ object|convert_length }} x {{ object|convert_width }}</li>
                        <li class="list-group-item">Volume: {{ object|convert_volume }}</li>
                        <li class="list-group-item">Wave Range: {{ object|convert_wave_range_start }} to {{ object|convert_wave_range_end }}</li>
                        <li class="list-group-item">Shaped by {{ board.shaper }}</li>
                        <li class="list-group-item">{{ board.year }} - {{ board.year }}</li>
                    </ul>
                </div>
            </div>
        </div>
        {% if object.author == user %}
        <div class="row">
            <div class="col-span-6"><a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'sb_quiver:board-update' object.id %}">Update</a>
            </div>
            <div class="col-span-6"><a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'sb_quiver:board-delete' object.id %}">Delete</a>
            </div>
        </div>
        {% endif %}

    </div>
</article>
{% endblock content %}

sb_goals/sb_quiver/templates/sb_quiver/board_form.html
{% extends "home/base.html" %}
{% load sb_quiver_extras %}
{% load crispy_forms_tags %}
{% block content %}
{% include "sb_quiver/quiver_header.html" %}
<div class="content-section nice-padding">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Surfboard Quiver</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Add</button>
        </div>
    </form>

</div>
{% endblock content %}

sb_goals/sb_quiver/templates/sb_quiver/home.html
{% extends "home/base.html" %}
{% load sb_quiver_extras %}
{% block content %}
{% include "sb_quiver/quiver_header.html" %}
<article class="media content-section nice-padding top-padding">
    <div class="container">
        <div class="row">
    {% for board in boards %}
            <div class="card mb-4 mx-4 box-shadow flex-even sb_card_min_width">
                <img class="card_image_centre_crop" src="{{ board.image.url }}" alt="{{ board.name }}">

                <div class="card-body">
                    <h5 class="card-title"> <h2><a class="article-title" href="{% url 'sb_quiver:board-detail' board.id %}">{{ board.title }}</a></h2></h5>
                    <p class="card-text">
                    <ul class="list-inline">
                        <li class="list-inline-item">Size: {{ board|convert_length }} x {{ board|convert_width }}</li>
                    </ul>
                    {{ board.notes }}
                    </p>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'sb_quiver:board-update' board.id %}">Edit</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</article>

    {% if is_paginated %}

        {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-5' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock content %}

sb_goals/sb_quiver/templates/sb_quiver/quiver_header.html
<header class="merged nice-padding">
    <div class="row row-flush">
        <div class="col1">
            <div class="avatar"><img src="{{ request.user.wagtail_userprofile.avatar.url }}" alt=""></div>
        </div>
        <div class="col9">
            <h1>Surfboard Quiver</h1>
            <div class="user-name">{{ username|safe }}</div>
        </div>
    </div>
</header>

sb_goals/sb_quiver/templates/sb_quiver/user_boards.html
{% extends "home/base.html" %}
{% load sb_quiver_extras %}
{% block content %}
{% include "sb_quiver/quiver_header.html" %}
    <h1 class="mb-3">{{ view.kwargs.username }} Surboard Quiver ({{ page_obj.paginator.count }})</h1>
{% for board in boards %}
<article class="media content-section nice-padding">
    <img class="rounded-circle article-img" src="{{ board.author.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'user-boards' board.author.username %}">{{ board.author }}</a>
            <small class="text-muted">{{ board.date_posted|date:"F d, Y" }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'sb_quiver:board-detail' board.id %}">{{ board.title }}</a></h2>
        <p class="article-content">{{ board.content }}</p>
    </div>
</article>
{% endfor %}
{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-5' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

{% endif %}
{% endblock content %}